config/routes.rb
Rails.application.routes.draw do


  root 'start#groups'
  
  get '/welcome',         to: 'start#welcome', as: 'welcome'
  get '/whats-your-name', to: 'start#name',    as: 'name'
  get '/start-game',      to: 'start#play',    as: 'play'
  

  get '/play',      to: 'game#play!', as: 'game_play'
  get '/finished',  to: 'game#finished!', as: 'game_finished'


  scope 'gestao' do 
    resources :results, path: 'resultados'
  end
end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :player
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/round.rb
class Round 
  include ActiveModel::Model

  IMAGE_TYPES = ['Animal', 'Humano', 'Objeto']
  IMAGE_IDS   = [0,0,0]


  def self.play!(options = {})
    @group  = options[:group_id]
    @player = options[:player]
    @index  = options[:index]
    @choice = options[:choice]

    case @group.to_i 
    when 1
      return false if @index.to_i == 90
      
      if @player == 1
          @play = Play.new
          @play.group_id  = @group
          @play.player_id = @player
          @play.choice_type = @choice
          @play.save
      end
    when 2
      if @player == 1
      end
      if @player == 2
      end
    when 3
      if @player == 1
      end
      if @player == 2
      end
    end
  end

  def self.turn!(index, group)
    if group.to_i == 1
      index
    else
      index = (index.to_i / 2)
      ((index.to_i / 2) == 0) ? 1 : index
    end
  end

  def self.player_turn!(index,group)
    if group.to_i == 1
      1
    else
      index.to_i % 2
    end
  end

  def self.images!(index)
    ids     = Array.new
    3.times { ids << rand(1...21) }

    [ids, IMAGE_TYPES.shuffle]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  before_action :validate_session!

  def play!
    if session[:play].nil?
      session[:play] = 1 
    else
      session[:play] = session[:play] + 1
    end

    @image_url = "http://tccgame.s3-website-sa-east-1.amazonaws.com/images/"
    @play = session[:play]

    @round  = Round.turn!(@play, session[:group_id])
    @turn   = Round.player_turn!(@play, session[:group_id])
    @images = Round.images!(@play)

    redirect_to game_finished_path unless Round.play!({index: @play, player: @turn, choice: params[:t], group_id: session[:group_id]})

  end

  def finish!
  end


  private

  def validate_session!
    redirect_to root_path if session[:player_id].nil?
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def index
  end
  
end
  

app/controllers/start_controller.rb
class StartController < ApplicationController
 
  def groups
    reset_session
  end

  def name
    if params[:group_id].present?
      session[:group_id] = params[:group_id]
      @group = session[:group_id]
    else
      redirect_to root_path
    end
  end

  def welcome
    if params[:data].present? && params[:data][:name].present?
      @player = Player.new
      @player.name = params[:data][:name]
      @player.group_id = session[:group_id]

      if @player.save
        session[:player_id] = @player.id
      else
        flash[:danger] = "Talvez sua internet falhou no envio dos dados, tente novamente."
        redirect_to name_path
      end
    else
      flash[:danger] = "Necessário informar seu nome!!"
      redirect_to name_path
    end
  end

  
  def play
  end

 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/game/finished!.html.haml
.container
  .row{style: "margin-top: 100px;"}
    .col-md-12{style: "text-align: center"}
      %h2
        %b 
          %p Parabéns! Você finalizou seu teste com sucesso!
  .row{style: "margin-top: 100px;"}
    .col-md-12{style: "text-align: center"}
      = link_to "Voltar", root_path, class: 'btn btn-success btn-lg'

app/views/game/play!.html.haml
- if @turn == 1
  :css
    img:hover {
        border:15px solid #79FF2C !important;
    }
.container
  .row
    .col-md-3
      %h1
        %b Rodada
        = @round
    .col-md-5
    .col-md-4{style: 'text-align: right'}
      %h1
        %b= "#{(@turn == 1) ? 'Sua vez!' : 'Vez do Computador'}"
  %hr/
  %br/
  .row
    .col-md-12
      .row
        .col-md-6{style: 'text-align: left'}
          = link_to image_tag("#{@image_url}#{@images[1][0]}#{@images[0][0]}.png", width: 220, class: "image-choice #{@images[1][0]}"), game_play_path(t: @images[1][0])
        .col-md-6{style: 'text-align: right'}
          = link_to image_tag("#{@image_url}#{@images[1][1]}#{@images[0][1]}.png", width: 220, class: "image-choice #{@images[1][1]}"), game_play_path(t: @images[1][1])
      .row
        .col-md-12{style: 'text-align: center'}
          = link_to image_tag("#{@image_url}#{@images[1][2]}#{@images[0][2]}.png", width: 220, class: "image-choice #{@images[1][2]}"), game_play_path(t: @images[1][2])

- if @turn == 0
  :javascript
    $(document).ready(function(){
      setInterval(function(){
        $(".#{@images[1][1]}").css('border', '15px solid #79FF2C');
      }, 1000);
      setInterval(function(){
        $(location).attr('href', "/play?t=#{@images[1][1]}");
      }, 2000);
    });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tcc</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/start/groups.html.haml
.container
  .row{style: "margin-top: 100px;"}
    .col-md-12{style: "text-align: center"}
      %h1
        %b Selecione um grupo para iniciar!
  .row{style: "margin-top: 150px;"}
    .col-md-12{style: "text-align: center"}
      .col-md-4
        = link_to "Iniciar Grupo 1", name_path(group_id: 1), class: 'btn btn-success btn-lg'
      .col-md-4
        = link_to "Iniciar Grupo 2", name_path(group_id: 2), class: 'btn btn-success btn-lg'
      .col-md-4
        = link_to "Iniciar Grupo 3", name_path(group_id: 3), class: 'btn btn-success btn-lg'

app/views/start/name.html.haml
.container
  .row{style: "margin-top: 100px;"}
    .col-md-12{style: "text-align: center"}
      %h1
        %b Qual é seu nome?
  .row{style: "margin-top: 80px;"}
    .col-md-12{style: "text-align: center"}
      = simple_form_for :data, url: welcome_path, method: :get do |f|
        = f.input :name, label: false, placeholder: "Digite aqui o seu nome!"
        = f.submit "Prosseguir!", name: nil, class: 'btn btn-success btn-lg'

app/views/start/play.html.haml
Vamos iniciar 

app/views/start/welcome.html.haml
.container
  .row{style: "margin-top: 100px;"}
    .col-md-12{style: "text-align: center"}
      %h2
        %b 
          %p A seguir você verá um conjunto de slides constituídos por três imagens. 
          %p Uma de um animal, uma de um objeto e uma de uma pessoa.
          %p Você deve apontar para a imagem do objeto para ganhar pontos.
          %p Ao final, você deve ter o maior número de pontos possível.
  .row{style: "margin-top: 100px;"}
    .col-md-12{style: "text-align: center"}
      = link_to "Iniciar Jogo!", game_play_path, class: 'btn btn-success btn-lg'